name: qrcodegenerator
description: A QRCode Generator app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  image: ^4.0.17
  image_gallery_saver: ^2.0.2
  image_picker: ^0.8.8
  mobile_scanner: ^3.2.0
  permission_handler: ^10.3.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  social_share: ^2.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
